on:
  push:

name: Tests

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run cargo fmt
        run: cargo fmt --all --check

      - name: Run cargo clippy
        run: cargo clippy --all-features -- -D warnings

      - name: Ensure the library compiles
        run: cargo build -p rust-automata --no-default-features --features "dsl"

      - name: Run tests
        env:
            RUST_BACKTRACE: 1
        run: cargo test
